feat: shortestOptionalPath() with configurable Edge types and directions to find shortest paths by srcId and dstId
nebula-contrib/ngbatis pull request #303
Opened 2024-06-02 17:42 UTC by n3A87

1、NebulaDaoBasic 的接口拓展shortestOptionalPath()函数，完成查找指定起始点和目的点之间最短路径的功能，允许用户自定义边的类型（Edge type）和方向（direction）
3、增加了对shortestOptionalPath()函数的测试部分代码

2024-06-05 04:24 UTC, CorvusYe requested changes
@n3A87 
很高兴看到你新的PR！
可能有一些小问题需要做一些修改，
完成后可以通过运行 ngbatis-demo 下的单元测试来确认功能的准确性。

cc: @knqiufan

2024-06-05 04:24 UTC, CorvusYe commented on src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasic.java
> -    methodModel.setResultType(ResultSet.class);
这部分的代码记得回滚下哈

2024-06-05 04:24 UTC, CorvusYe commented on src/main/resources/NebulaDaoBasic.xml
> +        @}
根据文档所约定的语法结构，这部分建议不采用循环的方式，
并在 `${e}` 的位置考虑使用 `${ isNotEmpty(edgeTypeList) ? ng.join(e) : '*' }` 的方式。

另外，功能开发完成时，可以试着运行单元测试，ngbatis-demo 下的单元测试以确定代码的稳健。

附Nebula find path语法约定：
```
FIND { SHORTEST | SINGLE SHORTEST | ALL | NOLOOP } PATH [WITH PROP] FROM <vertex_id_list> TO <vertex_id_list>
OVER <edge_type_list> [REVERSELY | BIDIRECT] 
[<WHERE clause>] [UPTO <N> {STEP|STEPS}] 
YIELD path as <alias>
[| ORDER BY $-.path] [| LIMIT <M>];

<vertex_id_list> ::=
    [vertex_id [, vertex_id] ...]
```

`<vertex_id_list>`：点 ID 列表。多个点用英文逗号（,）分隔。支持$-和$var。
`<edge_type_list>`：Edge type 列表。多个 Edge type 用英文逗号（,）分隔。*表示所有 Edge type。

2024-06-05 04:24 UTC, CorvusYe commented on ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/NebulaBasicDaoTests.java
> +    List<NgPath<String>> ngPaths = repository.shortestOptionalPath("吴小极", "刘小洲",Arrays.asList("like"),"BIDIRECT");
为了保证源码阅读的舒适度，项目引入了代码风格检查的插件。
这两行代码触发了一些风格上的规则。详情可见：https://github.com/nebula-contrib/ngbatis/actions/runs/9350174437/job/25820320996?pr=303#step:6:396

2024-06-07 11:59 UTC, n3A87 commented on src/main/resources/NebulaDaoBasic.xml
> +        @}
done

2024-06-07 11:59 UTC, n3A87 commented on ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/NebulaBasicDaoTests.java
> +    List<NgPath<String>> ngPaths = repository.shortestOptionalPath("吴小极", "刘小洲",Arrays.asList("like"),"BIDIRECT");
done

2024-06-07 11:59 UTC, n3A87 commented on src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasic.java
> -    methodModel.setResultType(ResultSet.class);
done

2024-06-10 12:09 UTC, CorvusYe approved these changes
LGTM

2024-06-10 12:23 UTC, merged