feat: add showSpaces function
nebula-contrib/ngbatis pull request #304
Opened 2024-06-09 10:33 UTC by n3A87

1、新增查看所有空间showSpaces方法
3、提供使用showSpaces方法的单元测试

2024-06-10 12:45 UTC, knqiufan requested changes
`showSpaces` 方法的返回值与返回类型相关代码的优化修改。

2024-06-10 12:45 UTC, knqiufan commented on src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasic.java
> +    return resultSet.toString();
这儿的返回值有些问题，`ResultSet` 直接 `toString` 返回的是个带有`ResultSet` 对象属性的字符串，而不是 space 名称。我的修改建议是：
1. 将查询到的结果从 `ResultSet` 中解析出来再返回；
2. `SHOW SPACES` 查询所有的 space ，所以可以考虑使用字符串数组作为返回类型。

2024-06-11 15:10 UTC, n3A87 commented on src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasic.java
> +    return resultSet.toString();
谢谢梵老师~已做修改

2024-06-11 17:23 UTC, knqiufan commented on src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasic.java
> +    return resultSet.toString();
great!

2024-06-11 17:26 UTC, knqiufan approved these changes

2024-06-11 17:39 UTC, merged